version: "3"

services:
  mysql:
    image: mysql:latest # プロダクトで使うならバージョンはlatestじゃないほうが良いです
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root # MySQLパスワード設定
      MYSQL_DATABASE: recordings # MySQLデータベース名設定
      TZ: "Asia/Tokyo"
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/my.cnf # MySQLの設定ファイル指定
    ports:
      - "3306:3306"